"""Generate ability_<lang>.dart maps from abilities_ru.json via Google translate.

Usage: python tool/gen_ability_xx.py es
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

from deep_translator import GoogleTranslator

ROOT = Path(__file__).resolve().parents[1]


def dart_escape(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("$", "\\$")
        .replace("\n", "\\n")
    )


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python tool/gen_ability_xx.py <lang>")
        sys.exit(1)
    lang = sys.argv[1]
    src = json.loads((ROOT / "tool/abilities_ru.json").read_text(encoding="utf-8"))
    titles = src["titles"]
    descs = src["descriptions"]
    keys = list(titles.keys())
    tr = GoogleTranslator(source="ru", target=lang)
    cache_path = ROOT / f"tool/abilities_{lang}_cache.json"
    cache = json.loads(cache_path.read_text(encoding="utf-8")) if cache_path.exists() else {}
    for i, k in enumerate(keys):
        entry = cache.get(k, {})
        if "title" not in entry:
            entry["title"] = tr.translate(titles[k])
            time.sleep(0.05)
        if "desc" not in entry:
            entry["desc"] = tr.translate(descs[k])
            time.sleep(0.08)
        cache[k] = entry
        if (i + 1) % 20 == 0:
            cache_path.write_text(json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8")
            print(f"{i+1}/{len(keys)}", flush=True)
    cache_path.write_text(json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8")
    lines = [
        f"// GENERATED by tool/gen_ability_xx.py {lang}",
        "import 'game_ability.dart';",
        "",
        f"const Map<GameAbility, String> kAbilityTitles{lang.capitalize()} = {{",
    ]
    for k in keys:
        lines.append(f"  GameAbility.{k}: '{dart_escape(cache[k]['title'])}',")
    lines += ["};", "", f"const Map<GameAbility, String> kAbilityDescriptions{lang.capitalize()} = {{"]
    for k in keys:
        lines.append(f"  GameAbility.{k}: '{dart_escape(cache[k]['desc'])}',")
    lines += ["};", ""]
    out = ROOT / f"lib/l10n/models/ability_{lang}.dart"
    out.write_text("\n".join(lines), encoding="utf-8")
    print("Wrote", out)


if __name__ == "__main__":
    main()
