"""Translate abilities_ru.json -> lib/l10n/models/ability_en.dart"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

from deep_translator import GoogleTranslator

ROOT = Path(__file__).resolve().parents[1]
src = json.loads((ROOT / "tool/abilities_ru.json").read_text(encoding="utf-8"))
titles: dict[str, str] = src["titles"]
descs: dict[str, str] = src["descriptions"]
cache_path = ROOT / "tool/abilities_en_cache.json"

TITLE_OVERRIDES = {
    "modeKingCenter": "Tour de France",
    "rookAstronomicon": "Astronomicon",
    "boardGolconda": "Golconda",
    "boardBaskerville": "Baskerville Effect",
    "boardFisher": "Fischer Chess",
    "boardFisherMadness": "Fischer Madness",
    "modeAtomic": "Atomic Chess",
    "modeCrazyhouse": "Crazyhouse",
    "modeDuckChess": "Duck Chess",
    "modeKriegspiel": "Kriegspiel",
    "pawnAirborne": "Airborne",
    "pawnRansom": "Ransom",
    "boardFogOfWar": "Fog of War",
}


def dart_escape(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("$", "\\$")
        .replace("\n", "\\n")
        .replace("\r", "")
    )


def log(msg: str) -> None:
    print(msg, flush=True)


translator = GoogleTranslator(source="ru", target="en")
cache: dict[str, dict[str, str]] = {}
if cache_path.exists():
    cache = json.loads(cache_path.read_text(encoding="utf-8"))


def translate_one(text: str) -> str:
    for attempt in range(5):
        try:
            out = translator.translate(text)
            if out and out.strip() and out not in {"RESULTS", "OPTION", "OPTIONS"}:
                return out
        except Exception as exc:
            log(f"  retry {attempt}: {exc}")
            time.sleep(1.0 * (attempt + 1))
    return text


keys = list(titles.keys())
log(f"Keys: {len(keys)}")

for i, k in enumerate(keys):
    entry = cache.get(k, {})
    changed = False
    if "title" not in entry:
        entry["title"] = TITLE_OVERRIDES.get(k) or translate_one(titles[k])
        changed = True
    elif k in TITLE_OVERRIDES:
        entry["title"] = TITLE_OVERRIDES[k]
        changed = True
    if "desc" not in entry:
        entry["desc"] = translate_one(descs[k])
        changed = True
        time.sleep(0.08)
    if changed:
        cache[k] = entry
        if (i + 1) % 10 == 0:
            cache_path.write_text(
                json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8"
            )
            log(f"  cached {i + 1}/{len(keys)}")

cache_path.write_text(json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8")
log("Writing dart…")

lines = [
    "// GENERATED by tool/gen_ability_en.py — do not edit by hand.",
    "import 'game_ability.dart';",
    "",
    "const Map<GameAbility, String> kAbilityTitlesEn = {",
]
for k in keys:
    lines.append(f"  GameAbility.{k}: '{dart_escape(cache[k]['title'])}',")
lines += [
    "};",
    "",
    "const Map<GameAbility, String> kAbilityDescriptionsEn = {",
]
for k in keys:
    lines.append(f"  GameAbility.{k}: '{dart_escape(cache[k]['desc'])}',")
lines += ["};", ""]

out = ROOT / "lib/l10n/models/ability_en.dart"
out.write_text("\n".join(lines), encoding="utf-8")
log(f"Wrote {out} titles={len(keys)} descs={len(keys)}")
sys.exit(0)
